"before_install":
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter

"language": node_js

"script": "grunt coverage"


"after_script":
  - codeclimate < test/coverage/lcov.info

