"before_install":
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter

"language": node_js

"script": "grunt bowercopy && grunt coverage"


"after_script":
  - codeclimate < coverage/unit_tests/lcov.info

